# -*- coding: utf-8 -*-
"""Introduçao a data science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-s5EfOn1efnfc8Lx7MUsoxkyiqQu4Odi
"""

import pandas as pd

notas = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/ml-latest-small/ratings.csv")
notas

notas.shape

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

notas["nota"].unique()

notas["nota"].value_counts()

notas["nota"].mean()

notas["nota"].plot(kind="hist")

notas["nota"].median()

mediana = notas['nota'].median()
media = notas["nota"].mean()
print(f"Mediana é {mediana}")
print(f"Média é {media}")

notas["nota"].describe()

import seaborn as sns

sns.boxplot(notas["nota"])

filmes = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/ml-latest-small/movies.csv")
filmes.columns = ["filmeId", "titulo", "generos"]
filmes.head()

notas.query("filmeId==1")["nota"].mean()

notas.query("filmeId==2")["nota"].mean()

medias_por_filme = notas.groupby("filmeId")['nota'].mean()
medias_por_filme.head()

medias_por_filme.plot(kind = 'hist')

sns.boxplot(medias_por_filme)

medias_por_filme.describe()

import matplotlib.pyplot as plt

sns.displot(medias_por_filme, kde = True)
plt.title("Histograma das médias dos filmes")
plt.show()

tmdb = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/tmdb_5000_movies.csv")
tmdb.head()

sns.displot(tmdb['revenue'])
plt.title("Distribuição da receita")
plt.show()

sns.displot(tmdb['budget'])
plt.title("Distribuição do orçamento dos filmes")
plt.show()

tmdb.info()

tmdb.describe()

com_faturamento = tmdb.query("revenue > 0")
sns.displot(com_faturamento['revenue'])

tmdb["original_language"].unique()

tmdb["original_language"].value_counts()

contagem_de_lingua = tmdb["original_language"].value_counts().to_frame().reset_index()
contagem_de_lingua.columns = ["original_language", "total"]
contagem_de_lingua.head()

sns.barplot(x = "original_language", y = "total", data = contagem_de_lingua)

total_de_outros_filmes_por_lingua = tmdb.query("original_language != 'en'")["original_language"].value_counts()
total_de_outros_filmes_por_lingua.head()

sns.countplot(data=tmdb.query("original_language != 'en'"), x = "original_language")

sns.countplot(data=tmdb.query("original_language != 'en'"),
              order=total_de_outros_filmes_por_lingua.index,
              x = "original_language")